import { Difficulty } from "@/types";
import {
  BookOpenCheck,
  LayoutDashboard,
  Lightbulb,
  MessageCircle,
  UserCheck,
} from "lucide-react";

export const user = {
  name: "John Doe",
  email: "johndoe@gmail.com",
  avatar: "/avatar.jpg",
  role: "Teacher",
};

export const NavItems = [
  {
    title: "Dashboard",
    url: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Quiz Generator",
    url: "/quizzes",
    icon: Lightbulb,
  },
  {
    title: "Assignment Checker",
    url: "/assignments",
    icon: BookOpenCheck,
  },
  {
    title: "Oral Test Simulation",
    url: "/orals",
    icon: MessageCircle,
  },
  {
    title: "Personalized Guidance",
    url: "/guidance",
    icon: UserCheck,
  },
];

export const Quizzes = [
  {
    id: "quiz-1",
    class_name: "10th Grade",
    subject: "Mathematics",
    topic: "Algebra",
    questions: [
      {
        id: "q1",
        text: "What is the output of `typeof null`?",
        options: [
          { id: "A", text: `"object"` },
          { id: "B", text: `"null"` },
          { id: "C", text: `"undefined"` },
          { id: "D", text: `"number"` },
        ],
        correctOptionId: "A",
      },
      {
        id: "q2",
        text: "Which method converts JSON to a JavaScript object?",
        options: [
          { id: "A", text: `JSON.stringify()` },
          { id: "B", text: `JSON.parse()` },
          { id: "C", text: `JSON.objectify()` },
          { id: "D", text: `JSON.convert()` },
        ],
        correctOptionId: "B",
      },
      {
        id: "q3",
        text: "What is the result of `0.1 + 0.2 === 0.3`?",
        options: [
          { id: "A", text: `true` },
          { id: "B", text: `false` },
          { id: "C", text: `undefined` },
          { id: "D", text: `NaN` },
        ],
        correctOptionId: "B",
      },
      {
        id: "q4",
        text: "Which of the following is a valid way to declare a variable in JavaScript?",
        options: [
          { id: "A", text: `var x = 10;` },
          { id: "B", text: `let y = 20;` },
          { id: "C", text: `const z = 30;` },
          { id: "D", text: `All of the above` },
        ],
        correctOptionId: "D",
      },
      {
        id: "q5",
        text: "What does the `===` operator do in JavaScript?",
        options: [
          { id: "A", text: `Checks for value equality` },
          { id: "B", text: `Checks for type and value equality` },
          { id: "C", text: `Checks for reference equality` },
          { id: "D", text: `None of the above` },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 5,
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.HARD,
    createdAt: new Date("2025-05-10"),
    additional_info_context:
      "This quiz covers basic concepts of algebra for beginners.",
  },
  {
    id: "quiz-2",
    class_name: "10th Grade",
    subject: "Science",
    topic: "Physics",
    questions: [
      {
        id: "q1",
        text: "What is the unit of force?",
        options: [
          { id: "A", text: "Newton" },
          { id: "B", text: "Joule" },
          { id: "C", text: "Pascal" },
          { id: "D", text: "Watt" },
        ],
        correctOptionId: "A",
      },
      {
        id: "q2",
        text: "What is the speed of light in a vacuum?",
        options: [
          { id: "A", text: "300,000 km/s" },
          { id: "B", text: "150,000 km/s" },
          { id: "C", text: "1,000,000 km/s" },
          { id: "D", text: "500,000 km/s" },
        ],
        correctOptionId: "A",
      },
      {
        id: "q3",
        text: "What is the formula for calculating kinetic energy?",
        options: [
          { id: "A", text: "KE = 0.5 * m * v^2" },
          { id: "B", text: "KE = m * g * h" },
          { id: "C", text: "KE = F * d" },
          { id: "D", text: "KE = m * a" },
        ],
        correctOptionId: "A",
      },
    ],
    num_questions: 3,
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.MEDIUM,
    createdAt: new Date("2025-05-15"),
  },
  {
    id: "quiz-4",
    class_name: "10th Grade",
    subject: "Geography",
    topic: "Continents and Oceans",
    questions: [
      {
        id: "q1",
        text: "Which is the largest continent by area?",
        options: [
          { id: "A", text: "Asia" },
          { id: "B", text: "Africa" },
          { id: "C", text: "Europe" },
          { id: "D", text: "North America" },
        ],
        correctOptionId: "A",
      },
      {
        id: "q2",
        text: "Which ocean is the deepest?",
        options: [
          { id: "A", text: "Atlantic Ocean" },
          { id: "B", text: "Indian Ocean" },
          { id: "C", text: "Pacific Ocean" },
          { id: "D", text: "Arctic Ocean" },
        ],
        correctOptionId: "C",
      },
      {
        id: "q3",
        text: "Which continent has the most countries?",
        options: [
          { id: "A", text: "Asia" },
          { id: "B", text: "Africa" },
          { id: "C", text: "Europe" },
          { id: "D", text: "South America" },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 3,
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.EASY,
    createdAt: new Date("2025-05-18"),
    additional_info_context:
      "This quiz covers basic knowledge of continents and oceans.",
  },
  {
    id: "quiz-5",
    class_name: "10th Grade",
    subject: "History",
    topic: "World Wars",
    questions: [
      {
        id: "q1",
        text: "When did World War I begin?",
        options: [
          { id: "A", text: "1914" },
          { id: "B", text: "1918" },
          { id: "C", text: "1939" },
          { id: "D", text: "1945" },
        ],
        correctOptionId: "A",
      },
      {
        id: "q2",
        text: "Who was the leader of Nazi Germany during World War II?",
        options: [
          { id: "A", text: "Adolf Hitler" },
          { id: "B", text: "Winston Churchill" },
          { id: "C", text: "Joseph Stalin" },
          { id: "D", text: "Franklin D. Roosevelt" },
        ],
        correctOptionId: "A",
      },
    ],
    num_questions: 2,
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.MEDIUM,
    createdAt: new Date("2025-05-20"),
  },
  {
    id: "quiz-6",
    class_name: "10th Grade",
    subject: "English",
    topic: "Grammar",
    questions: [
      {
        id: "q1",
        text: "Which of the following is a noun?",
        options: [
          { id: "A", text: "Run" },
          { id: "B", text: "Beautiful" },
          { id: "C", text: "Happiness" },
          { id: "D", text: "Quickly" },
        ],
        correctOptionId: "C",
      },
      {
        id: "q2",
        text: "What is the past tense of 'go'?",
        options: [
          { id: "A", text: "Goes" },
          { id: "B", text: "Went" },
          { id: "C", text: "Gone" },
          { id: "D", text: "Going" },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 2,
    deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.HARD,
    createdAt: new Date("2025-05-22"),
  },
  {
    id: "quiz-7",
    class_name: "10th Grade",
    subject: "Biology",
    topic: "Human Anatomy",
    questions: [
      {
        id: "q1",
        text: "What is the largest organ in the human body?",
        options: [
          { id: "A", text: "Heart" },
          { id: "B", text: "Liver" },
          { id: "C", text: "Skin" },
          { id: "D", text: "Brain" },
        ],
        correctOptionId: "C",
      },
      {
        id: "q2",
        text: "What is the function of red blood cells?",
        options: [
          { id: "A", text: "Transport oxygen" },
          { id: "B", text: "Fight infections" },
          { id: "C", text: "Clot blood" },
          { id: "D", text: "Store energy" },
        ],
        correctOptionId: "A",
      },
    ],
    num_questions: 2,
    deadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.MEDIUM,
    createdAt: new Date("2025-05-25"),
  },
  {
    id: "quiz-8",
    class_name: "10th Grade",
    subject: "Mathematics",
    topic: "Geometry",
    questions: [
      {
        id: "q1",
        text: "What is the sum of the interior angles of a triangle?",
        options: [
          { id: "A", text: "180°" },
          { id: "B", text: "360°" },
          { id: "C", text: "90°" },
          { id: "D", text: "270°" },
        ],
        correctOptionId: "A",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.EASY,
    createdAt: new Date("2025-05-28"),
  },
  {
    id: "quiz-9",
    class_name: "10th Grade",
    subject: "Science",
    topic: "Chemistry",
    questions: [
      {
        id: "q1",
        text: "What is the chemical symbol for Sodium?",
        options: [
          { id: "A", text: "Na" },
          { id: "B", text: "So" },
          { id: "C", text: "S" },
          { id: "D", text: "Sn" },
        ],
        correctOptionId: "A",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.EASY,
    createdAt: new Date("2025-04-30"),
  },
  {
    id: "quiz-10",
    class_name: "10th Grade",
    subject: "Computer Science",
    topic: "Data Types",
    questions: [
      {
        id: "q1",
        text: "Which of the following is a primitive data type in JavaScript?",
        options: [
          { id: "A", text: "Array" },
          { id: "B", text: "Object" },
          { id: "C", text: "String" },
          { id: "D", text: "Function" },
        ],
        correctOptionId: "C",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.MEDIUM,
    createdAt: new Date("2025-05-20"),
  },
  {
    id: "quiz-11",
    class_name: "10th Grade",
    subject: "English",
    topic: "Vocabulary",
    questions: [
      {
        id: "q1",
        text: "What is the synonym of 'happy'?",
        options: [
          { id: "A", text: "Sad" },
          { id: "B", text: "Angry" },
          { id: "C", text: "Joyful" },
          { id: "D", text: "Tired" },
        ],
        correctOptionId: "C",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.EASY,
    createdAt: new Date("2025-05-20"),
  },
  {
    id: "quiz-12",
    class_name: "10th Grade",
    subject: "History",
    topic: "Indian Independence",
    questions: [
      {
        id: "q1",
        text: "In which year did India gain independence?",
        options: [
          { id: "A", text: "1945" },
          { id: "B", text: "1947" },
          { id: "C", text: "1950" },
          { id: "D", text: "1930" },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.EASY,
    createdAt: new Date("2025-05-23"),
  },
  {
    id: "quiz-13",
    class_name: "10th Grade",
    subject: "Mathematics",
    topic: "Trigonometry",
    questions: [
      {
        id: "q1",
        text: "What is sin(90°)?",
        options: [
          { id: "A", text: "0" },
          { id: "B", text: "1" },
          { id: "C", text: "0.5" },
          { id: "D", text: "Undefined" },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.MEDIUM,
    createdAt: new Date("2025-05-23"),
  },
  {
    id: "quiz-14",
    class_name: "10th Grade",
    subject: "Civics",
    topic: "Democracy",
    questions: [
      {
        id: "q1",
        text: "Which of the following is a feature of democracy?",
        options: [
          { id: "A", text: "One-party rule" },
          { id: "B", text: "Free and fair elections" },
          { id: "C", text: "Dictatorship" },
          { id: "D", text: "Military rule" },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.EASY,
    createdAt: new Date("2025-05-24"),
  },
  {
    id: "quiz-15",
    class_name: "10th Grade",
    subject: "Economics",
    topic: "Money and Credit",
    questions: [
      {
        id: "q1",
        text: "Which institution issues currency in India?",
        options: [
          { id: "A", text: "SBI" },
          { id: "B", text: "RBI" },
          { id: "C", text: "Finance Ministry" },
          { id: "D", text: "NABARD" },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.MEDIUM,
    createdAt: new Date("2025-03-23"),
  },
  {
    id: "quiz-16",
    class_name: "10th Grade",
    subject: "Science",
    topic: "Electricity",
    questions: [
      {
        id: "q1",
        text: "What is the SI unit of electric current?",
        options: [
          { id: "A", text: "Volt" },
          { id: "B", text: "Ampere" },
          { id: "C", text: "Ohm" },
          { id: "D", text: "Watt" },
        ],
        correctOptionId: "B",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.MEDIUM,
    createdAt: new Date("2025-04-27"),
  },
  {
    id: "quiz-17",
    class_name: "10th Grade",
    subject: "Biology",
    topic: "Nutrition",
    questions: [
      {
        id: "q1",
        text: "Which vitamin is known as the sunshine vitamin?",
        options: [
          { id: "A", text: "Vitamin A" },
          { id: "B", text: "Vitamin B" },
          { id: "C", text: "Vitamin C" },
          { id: "D", text: "Vitamin D" },
        ],
        correctOptionId: "D",
      },
    ],
    num_questions: 1,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    difficulty: Difficulty.EASY,
    createdAt: new Date("2025-02-29"),
  },
];
